# Closed loop wave - circular wave pattern

waypoints:
  # Circular wave pattern (closed loop)
  - [0.0, 0.0]
  - [5.0, 3.0]
  - [10.0, 4.0]
  - [15.0, 3.0]
  - [20.0, 0.0]
  - [23.0, -3.0]
  - [24.0, -6.0]
  - [23.0, -9.0]
  - [20.0, -12.0]
  - [15.0, -13.0]
  - [10.0, -12.0]
  - [5.0, -9.0]
  - [2.0, -6.0]
  - [1.0, -3.0]

path_settings:
  interpolation: 'cubic'
  resolution: 50
  closed_path: true  # Loop back to start
