# Wave-shaped path configurations for testing
# Multiple wave patterns to choose from

waypoints:
  # High-frequency wave (shorter wavelength, more oscillations)
  - [0.0, 0.0]
  - [3.0, 2.5]
  - [6.0, 0.0]
  - [9.0, -2.5]
  - [12.0, 0.0]
  - [15.0, 2.5]
  - [18.0, 0.0]
  - [21.0, -2.5]
  - [24.0, 0.0]
  - [27.0, 2.5]
  - [30.0, 0.0]
  - [33.0, -2.5]
  - [36.0, 0.0]
  - [39.0, 2.5]
  - [42.0, 0.0]
  - [45.0, -2.5]
  - [48.0, 0.0]

path_settings:
  interpolation: 'cubic'
  resolution: 50
  closed_path: false
